#!/usr/bin/env node
/**
 * Builds the stylesheets the package ships.
 *
 * Runs PostCSS through its API rather than the Tailwind CLI so the plugin list
 * is explicit: the CLI additionally picks up postcss.config.js, which would
 * apply Tailwind a second time with the DEV config and silently reintroduce the
 * global preflight this build exists to remove.
 *
 * Emits into dist/:
 *   tokens.css      design tokens for both themes — load once, globally
 *   tablewright.css scoped reset + component globals + utilities
 *   styles.css      the two above concatenated, for a one-import start
 *   preflight.css   Tailwind's global reset, opt-in
 *   fonts.css       the web-font @import, opt-in
 *
 * Order inside tablewright.css is load-bearing: reset first, then component
 * globals, then utilities. The reset sits at exactly (0,1,0) — one real class
 * plus a :where() element list — so it outranks a host reset that names bare
 * elements while still losing to any utility on source order.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import autoprefixer from "autoprefixer";
import postcss from "postcss";
import tailwindcss from "tailwindcss";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "src", "css");
const dist = join(root, "dist");

const buildConfig = (await import(join(root, "tailwind.build.config.js"))).default;

const read = (name) => readFileSync(join(src, name), "utf8");

async function run(css, config, from) {
  const result = await postcss([tailwindcss(config), autoprefixer()]).process(css, { from });
  for (const warning of result.warnings()) console.warn(`  warn: ${warning.toString()}`);
  return result.css;
}

mkdirSync(dist, { recursive: true });

const banner = (what) =>
  `/* @undevy-org/tablewright — ${what}. Generated by scripts/build-css.mjs; do not edit. */\n`;

// Utilities only: no preflight, no stories in the content scan.
const utilities = await run(
  "@tailwind components;\n@tailwind utilities;\n",
  buildConfig,
  join(src, "tailwind.css"),
);

// Tailwind's global reset, shipped separately so importing it is a choice.
// Compiled from a STOCK config, not this repo's: preflight bakes
// theme.fontFamily.sans and .mono into `html` and `code`, so building it with
// the dev config would make an opt-in reset silently retype the host page in
// Inter and JetBrains Mono — the one thing the scoping design exists to avoid.
const preflight = await run("@tailwind base;\n", { content: [{ raw: "" }] }, join(src, "tailwind.css"));

const tokens = banner("design tokens") + read("tokens.css");
const tablewright =
  banner("scoped reset, component globals and utilities") +
  read("reset.css") +
  "\n" +
  read("scrollbar.css") +
  "\n" +
  utilities;

const artifacts = {
  "tokens.css": tokens,
  "tablewright.css": tablewright,
  "styles.css": banner("tokens + components, single import") + tokens + "\n" + tablewright,
  "preflight.css": banner("Tailwind preflight, opt-in") + preflight,
  "fonts.css": read("fonts.css"),
};

for (const [name, content] of Object.entries(artifacts)) {
  writeFileSync(join(dist, name), content);
  const kb = (Buffer.byteLength(content) / 1024).toFixed(1);
  console.log(`  dist/${name.padEnd(16)} ${kb.padStart(6)} KB`);
}

// The one failure this build can produce silently: utilities compiled with an
// empty content scan (a bad glob) still write a valid, useless stylesheet.
// String.raw, not a RegExp: Tailwind escapes the class name in the output as
// `.bg-\[var\(--bg-surface\)\]`, so the backslashes are literal CSS text.
const probe = String.raw`.bg-\[var\(--bg-surface\)\]`;
if (!utilities.includes(probe)) {
  console.error(
    "\nFAIL: compiled utilities do not contain .bg-[var(--bg-surface)] — the content" +
      " globs in tailwind.build.config.js matched nothing. dist would ship unstyled.",
  );
  process.exit(1);
}
// The second failure mode is the one this whole CSS layout exists to prevent:
// a rule in the shipped stylesheet that reaches outside `.tablewright`. That is
// what a leaked preflight looks like (`*`, `html`, `body`, `h1`, `button`, …),
// and it is what would restyle the host application. Checking corePlugins here
// would prove nothing — the utilities entry carries no `@tailwind base`, so the
// flag cannot express the defect. Check the artifact instead.
// Split a selector list on top-level commas only: the commas inside
// `:where(p, figure, blockquote)` do not separate selectors, and treating them
// as if they did reports every one of those element names as unscoped.
function splitSelectorList(list) {
  const parts = [];
  let depth = 0;
  let current = "";
  for (const ch of list) {
    if (ch === "(" || ch === "[") depth += 1;
    else if (ch === ")" || ch === "]") depth -= 1;
    if (ch === "," && depth === 0) {
      parts.push(current);
      current = "";
    } else current += ch;
  }
  parts.push(current);
  return parts;
}

const unscoped = [];
const withoutComments = tablewright.replace(/\/\*[\s\S]*?\*\//g, "");
for (const [, prelude] of withoutComments.matchAll(/([^{}]+)\{/g)) {
  const head = prelude.trim();
  if (head.startsWith("@")) continue; // at-rule prelude, not a selector
  for (const selector of splitSelectorList(head)) {
    const s = selector.trim();
    if (!s || s === "from" || s === "to" || /^\d+(\.\d+)?%$/.test(s)) continue;
    const scoped = s.includes(".tablewright") || s.startsWith(".");
    if (!scoped) unscoped.push(s);
  }
}
if (unscoped.length > 0) {
  console.error(
    `\nFAIL: ${unscoped.length} rule(s) in tablewright.css address elements directly rather than` +
      ` through a class — a leaked preflight looks exactly like this and would restyle the host` +
      ` page:\n  ${[...new Set(unscoped)].slice(0, 10).join("\n  ")}`,
  );
  process.exit(1);
}
// Third guard: hand-authored CSS must actually be scoped, and the scope class
// must carry specificity.
//
// The second guard above cannot express this. It accepts any selector starting
// with "." because the Tailwind-generated utilities are bare class selectors by
// construction and must pass — which means a hand-written global class would
// pass too, on a technicality, under a message claiming everything is scoped to
// .tablewright. So the hand-authored files are checked separately and strictly:
// every selector must name .tablewright OUTSIDE any :where(). Outside, because
// `:where(.tablewright)` drops the rule to specificity (0,0,0), where a host
// stylesheet's plain `button, input { border: none }` beats it and every control
// in the kit loses its border — silently, with every other check still green.
function stripWhere(selector) {
  let out = "";
  for (let i = 0; i < selector.length; i++) {
    if (selector.startsWith(":where(", i)) {
      let depth = 0;
      for (; i < selector.length; i++) {
        if (selector[i] === "(") depth += 1;
        else if (selector[i] === ")" && --depth === 0) break;
      }
      continue;
    }
    out += selector[i];
  }
  return out;
}

// Anchored: ".tablewright-legacy" contains the substring but is a different
// class and would be misread as scoped.
const SCOPE_CLASS = /\.tablewright(?![\w-])/;

const weak = [];
for (const file of ["reset.css", "scrollbar.css"]) {
  for (const [, prelude] of read(file).replace(/\/\*[\s\S]*?\*\//g, "").matchAll(/([^{}]+)\{/g)) {
    for (const selector of splitSelectorList(prelude.trim())) {
      const s = selector.trim();
      if (!s || s.startsWith("@")) continue;
      if (!SCOPE_CLASS.test(stripWhere(s))) weak.push(`${file}: ${s}`);
    }
  }
}
if (weak.length > 0) {
  console.error(
    `\nFAIL: ${weak.length} hand-authored selector(s) are not scoped to .tablewright with a real` +
      ` class — they would ship as global rules, or as a reset a host stylesheet beats:\n  ` +
      [...new Set(weak)].slice(0, 10).join("\n  "),
  );
  process.exit(1);
}
console.log("  checks: utilities present, no element-level rules, hand-authored CSS scoped");
